name: SudoSigns
version: 1.1.1
author: MylesMor
main: dev.mylesmor.sudosigns.SudoSigns
softdepend: [Multiverse-Core, Vault, PlaceholderAPI]
api-version: 1.13
commands:
  sudosigns:
    description: Opens the SudoSigns help menu.
    aliases: [sudosign, ss]
